export const routes = {
  unauthorized: {
    index: '/unauthorized',
  },
  dashboard: {
    index: '/dashboard',
  },
  profil: {
    index: '/profil',
    ubahPassword: '/profil/ubah-password',
  },
  diagramJaringan: {
    index: '/diagram-jaringan',
    posting: (slug: string) => `/diagram-jaringan/${slug}/posting`,
    clone: (slug: string) => `/diagram-jaringan/${slug}/clone`,
  },
  pindahId: {
    index: '/pindah-id',
  },
  bonus: {
    index: '/bonus',
    history: '/bonus/history',
  },
  lihatPin: {
    index: '/lihat-pin',
  },
  requestPin: {
    index: '/request-pin',
    history: '/history-request-pin',
  },
  generatePin: {
    index: '/generate-pin',
    history: '/generate-pin/history',
  },
  transferPin: {
    index: '/transfer-pin',
    history: '/transfer-pin/history',
  },
  postingPin: {
    index: '/posting-pin',
    history: '/posting-pin/history',
  },
  withdrawalGaji: {
    index: '/withdrawal-gaji',
    history: '/withdrawal-gaji/history',
    withdrawal: '/withdrawal-gaji/withdrawal',
  },
  withdrawalBonus: {
    index: '/withdrawal-bonus',
    historyRow: (slug: string) => `/withdrawal-bonus/${slug}/history`,
    withdrawalRow: (slug: string) => `/withdrawal-bonus/${slug}/withdrawal`,
    history: '/withdrawal-bonus/history',
  },
  produk: {
    index: '/produk',
    detail: (slug: string) => `/produk/${slug}`,
    history: '/produk/history',
    keranjang: '/produk/keranjang',
    checkout: '/produk/checkout',
    pesanan: {
      index: '/produk/pesanan',
      detail: (id: string) => `/produk/pesanan/${id}`,
    },
    pesananStockist: {
      index: '/produk/pesanan-stockist',
      detail: (id: string) => `/produk/pesanan-stockist/${id}`,
    },
  },
  kelolaProduk: {
    index: '/produk/kelola',
    transaksi: '/produk/transaksi',
  },
  stockist: {
    index: '/stockist',
    daftar: '/stockist/daftar',
    list: '/stockist/list',
  },
  kontak: {
    index: '/kontak',
  },
  promo: {
    index: '/promo',
  },
  download: {
    index: '/download',
  },
  profilPerusahaan: {
    index: '/profil-perusahaan',
  },
  eCommerce: {
    dashboard: '/ecommerce',
    products: '/ecommerce/products',
    createProduct: '/ecommerce/products/create',
    productDetails: (slug: string) => `/ecommerce/products/${slug}`,
    ediProduct: (slug: string) => `/ecommerce/products/${slug}/edit`,
    categories: '/ecommerce/categories',
    createCategory: '/ecommerce/categories/create',
    editCategory: (id: string) => `/ecommerce/categories/${id}/edit`,
    orders: '/ecommerce/orders',
    createOrder: '/ecommerce/orders/create',
    orderDetails: (id: string) => `/ecommerce/orders/${id}`,
    editOrder: (id: string) => `/ecommerce/orders/${id}/edit`,
    reviews: '/ecommerce/reviews',
    shop: '/ecommerce/shop',
    cart: '/ecommerce/cart',
    checkout: '/ecommerce/checkout',
    trackingId: (id: string) => `/ecommerce/tracking/${id}`,
  },
  searchAndFilter: {
    realEstate: '/search/real-estate',
    nft: '/search/nft',
    flight: '/search/flight',
  },
  support: {
    dashboard: '/support',
    inbox: '/support/inbox',
    supportCategory: (category: string) => `/support/inbox/${category}`,
    messageDetails: (id: string) => `/support/inbox/${id}`,
    snippets: '/support/snippets',
    createSnippet: '/support/snippets/create',
    viewSnippet: (id: string) => `/support/snippets/${id}`,
    editSnippet: (id: string) => `/support/snippets/${id}/edit`,
    templates: '/support/templates',
    createTemplate: '/support/templates/create',
    viewTemplate: (id: string) => `/support/templates/${id}`,
    editTemplate: (id: string) => `/support/templates/${id}/edit`,
  },
  logistics: {
    dashboard: '/logistics',
    shipmentList: '/logistics/shipments',
    customerProfile: '/logistics/customer-profile',
    createShipment: '/logistics/shipments/create',
    editShipment: (id: string) => `/logistics/shipments/${id}/edit`,
    shipmentDetails: (id: string) => `/logistics/shipments/${id}`,
    tracking: (id: string) => `/logistics/tracking/${id}`,
  },
  appointment: {
    dashboard: '/appointment',
    appointmentList: '/appointment/list',
  },
  crm: {
    dashboard: '/crm',
  },
  affiliate: {
    dashboard: 'https://isomorphic-dnd.vercel.app',
  },
  executive: {
    dashboard: '/executive',
  },
  project: {
    dashboard: '/project',
  },
  socialMedia: {
    dashboard: '/social-media',
  },
  jobBoard: {
    dashboard: '/job-board',
    jobFeed: '/job-board/feed',
  },
  analytics: '/analytics',
  financial: {
    dashboard: '/financial',
  },
  file: {
    dashboard: '/file',
    manager: '/file-manager',
    upload: '/file-manager/upload',
    create: '/file-manager/create',
  },
  pos: {
    index: '/point-of-sale',
  },
  eventCalendar: '/event-calendar',
  rolesPermissions: '/roles-permissions',
  invoice: {
    home: '/invoice',
    create: '/invoice/create',
    details: (id: string) => `/invoice/${id}`,
    edit: (id: string) => `/invoice/${id}/edit`,
    builder: '/invoice/builder',
  },
  imageViewer: '/image-viewer',
  widgets: {
    cards: '/widgets/cards',
    icons: '/widgets/icons',
    charts: '/widgets/charts',
    maps: '/widgets/maps',
    banners: '/widgets/banners',
  },
  tables: {
    basic: '/tables/basic',
    collapsible: '/tables/collapsible',
    enhanced: '/tables/enhanced',
    pagination: '/tables/pagination',
    search: '/tables/search',
    stickyHeader: '/tables/sticky-header',
    resizable: '/tables/resizable',
    pinning: '/tables/pinning',
    dnd: '/tables/dnd',
  },
  // multiStep: '/multi-step',
  forms: {
    profileSettings: '/forms/profile-settings',
    notificationPreference: '/forms/profile-settings/notification',
    personalInformation: '/forms/profile-settings/profile',
    newsletter: '/forms/newsletter',
  },
  emailTemplates: '/email-templates',
  profile: '/profile',
  welcome: '/welcome',
  comingSoon: '/coming-soon',
  accessDenied: '/access-denied',
  notFound: '/not-found',
  maintenance: '/maintenance',
  blank: '/blank',
  auth: {
    signUp1: '/auth/sign-up-1',
    signUp2: '/auth/sign-up-2',
    signUp3: '/auth/sign-up-3',
    signUp4: '/auth/sign-up-4',
    signUp5: '/auth/sign-up-5',
    // sign in
    signIn1: '/auth/sign-in-1',
    signIn2: '/auth/sign-in-2',
    signIn3: '/auth/sign-in-3',
    signIn4: '/auth/sign-in-4',
    signIn5: '/auth/sign-in-5',
    // forgot password
    forgotPassword1: '/auth/forgot-password-1',
    forgotPassword2: '/auth/forgot-password-2',
    forgotPassword3: '/auth/forgot-password-3',
    forgotPassword4: '/auth/forgot-password-4',
    forgotPassword5: '/auth/forgot-password-5',
    // OTP
    otp1: '/auth/otp-1',
    otp2: '/auth/otp-2',
    otp3: '/auth/otp-3',
    otp4: '/auth/otp-4',
    otp5: '/auth/otp-5',
  },
  signIn: '/signin',
};
